### ISSUE TITLE
Downgrade?

### ISSUE THREAD

**Issue by ManicQuinn** [Gibatron/reel-fishing#2]
Any plans to downgrade to 1.20.1? I wanna use this mod but a lot of my mods are not up to date with 1.20.4, and fishing is the only mod that is on 1.20.4, at least for my list of mods(apart from optimizations)

**Comment by noWickedfortheRest** [comment]
Potentially in the future, at the moment I'm focusing on implementing several features I didn't have time for during Modfest. So if I do backport it would happen after said features are added.

**Comment by ManicQuinn** [comment]
> Potentially in the future, at the moment I'm focusing on implementing several features I didn't have time for during Modfest. So if I do backport it would happen after said features are added.

Alright, thank you, hoping for the best <3

**Comment by whatamaniac** [comment]
I love the way this mod works. And it also fits with my modpack. But the only problem is.. my modpack is 1.20.1 based. Would love to see this mod get a 1.20.1 downgrade after the new features are added ^_^ Looking forward for it.
